### ISSUE TITLE
Fix NSInvalidArgumentException in + [PFNetworkingUtils networkThreadMain], line 32

### ISSUE THREAD

**Issue by bryansum** [bryansum/leftoverswap#10]
## Stacktrace

<pre>PFNetworkingUtils;networkThreadMain;PFNetworkingUtils.m;32</pre>

## Reason

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM didTimeout]: unrecognized selector sent to instance 0x18ff0390'
## Link to HockeyApp
- [https://rink.hockeyapp.net/manage/apps/39845/crash_reasons/8431194](https://rink.hockeyapp.net/manage/apps/39845/crash_reasons/8431194)

**Comment by igorgrikin** [comment]
Hi, Did you solve the issue?
I have similar issue and I thought it's due to [somepfquery find] timeout.
What's your idea regarding this crash?

**Comment by revolter** [comment]
Why is this here, and not in Parse's repository?
